### PR TITLE
Fix/tracker refactor

### PR DESCRIPTION
**Pull request by Anatoliy-F**
- Moved tracker functionality to separate service
- Added event type enum
- Added countdown to browser tab

### CODE REVIEW

**Review by Sihuta — APPROVED** [review]

**Review by Sihuta — CHANGES_REQUESTED** [review]
There is a bug in the tracker component. 3-digit minutes are not displayed correctly:
image

**Comment by Anatoliy-F** [comment]
> There is a bug in the tracker component. 3-digit minutes are not displayed correctly: image

We really can use pomodoro duration above 1 hour?
If yes - we need to  add field that represent hours in tracker view, but we really need it? one hour of concentration without short break?

**Comment by Vartanchik** [comment]
I think that should be some upper limit on pomodoro/breaks time(just add validation for this pop-up). It can be 60 minutes.

**Comment by Sihuta** [comment]
> I think that should be some upper limit on pomodoro/breaks time(just add validation for this pop-up). It can be 60 minutes.

Ok, I'll edit the max values for settings validators.

**Review by Sihuta — APPROVED** [review]

**Review by Vartanchik — APPROVED** [review]

**Review by kkkkkssst — APPROVED** [review]

**Review by BaseCampGL2023 — APPROVED** [review]

**Pull request merged**
